package Vista;


import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luism
 */
public class Principal extends javax.swing.JFrame {

    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProduct = new javax.swing.JMenu();
        itemNewProduct = new javax.swing.JMenuItem();
        itemSearchProduct = new javax.swing.JMenuItem();
        itemUpdateProduct = new javax.swing.JMenuItem();
        itemDeleteProduct = new javax.swing.JMenuItem();
        menuColors = new javax.swing.JMenu();
        itemViewColor = new javax.swing.JMenuItem();
        itemAddColor = new javax.swing.JMenuItem();
        menuUsers = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSale = new javax.swing.JMenu();
        itemSale = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/int-tarjetacredito6.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 14)); // NOI18N

        menuProduct.setText("Productos");

        itemNewProduct.setText("Añadir nuevo");
        menuProduct.add(itemNewProduct);

        itemSearchProduct.setText("Buscar producto");
        menuProduct.add(itemSearchProduct);

        itemUpdateProduct.setText("Actulizar producto");
        itemUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateProductActionPerformed(evt);
            }
        });
        menuProduct.add(itemUpdateProduct);

        itemDeleteProduct.setText("Borrar producto");
        menuProduct.add(itemDeleteProduct);

        jMenuBar1.add(menuProduct);

        menuColors.setText("Colores");

        itemViewColor.setText("Ver Lista");
        menuColors.add(itemViewColor);

        itemAddColor.setText("Agregar Color");
        menuColors.add(itemAddColor);

        jMenuBar1.add(menuColors);

        menuUsers.setText("Usuarios");

        jMenu1.setText("Usuarios Sistema");
        menuUsers.add(jMenu1);

        jMenuItem1.setText("Usuarios Página");
        menuUsers.add(jMenuItem1);

        jMenuBar1.add(menuUsers);

        menuSale.setText("Ventas");

        itemSale.setText("Lista de Ventas");
        menuSale.add(itemSale);

        jMenuBar1.add(menuSale);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUpdateProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Toolkit t = Toolkit.getDefaultToolkit();
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
System.out.println("Tu resolución es de " + screenSize.width + "x" + screenSize.height);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAddColor;
    private javax.swing.JMenuItem itemDeleteProduct;
    private javax.swing.JMenuItem itemNewProduct;
    private javax.swing.JMenuItem itemSale;
    private javax.swing.JMenuItem itemSearchProduct;
    private javax.swing.JMenuItem itemUpdateProduct;
    private javax.swing.JMenuItem itemViewColor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuColors;
    private javax.swing.JMenu menuProduct;
    private javax.swing.JMenu menuSale;
    private javax.swing.JMenu menuUsers;
    // End of variables declaration//GEN-END:variables
}
