package Vista;


import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luism
 */
public class Principal extends javax.swing.JFrame {

    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemNewProduct = new javax.swing.JMenuItem();
        itemSearchProduct = new javax.swing.JMenuItem();
        itemUpdateProduct = new javax.swing.JMenuItem();
        itemDeleteProduct = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemViewColor = new javax.swing.JMenuItem();
        itemAddColor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Productos");

        itemNewProduct.setText("Añadir nuevo");
        jMenu1.add(itemNewProduct);

        itemSearchProduct.setText("Buscar producto");
        jMenu1.add(itemSearchProduct);

        itemUpdateProduct.setText("Actulizar producto");
        itemUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateProductActionPerformed(evt);
            }
        });
        jMenu1.add(itemUpdateProduct);

        itemDeleteProduct.setText("Borrar producto");
        jMenu1.add(itemDeleteProduct);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Colores");

        itemViewColor.setText("Ver Lista");
        jMenu2.add(itemViewColor);

        itemAddColor.setText("Agregar Color");
        jMenu2.add(itemAddColor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Categorías");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Usuarios");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUpdateProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Toolkit t = Toolkit.getDefaultToolkit();
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
System.out.println("Tu resolución es de " + screenSize.width + "x" + screenSize.height);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAddColor;
    private javax.swing.JMenuItem itemDeleteProduct;
    private javax.swing.JMenuItem itemNewProduct;
    private javax.swing.JMenuItem itemSearchProduct;
    private javax.swing.JMenuItem itemUpdateProduct;
    private javax.swing.JMenuItem itemViewColor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
